version: '3.0'

services:
  falah-jeniusar:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - '3001:8000'
    networks:
      - jenius_ar
    volumes:
      - '.:/var/www'
    depends_on:
      - falah-jeniusar-db

  falah-jeniusar-db:
    image: 'mariadb'
    networks:
      - jenius_ar
    volumes:
      - './docker/sql:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ROOT_PASSWORD: 'eaudeparfum'
      MYSQL_DATABASE: 'jeniusar'
      MYSQL_USER: 'jenius'
      MYSQL_PASSWORD: 'j3n!us909'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

networks:
  jenius_ar:
    driver: bridge
